# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Godirb < Formula
  desc "Fast and easy-to-use directory brute-forcer written in go"
  homepage "https://github.com/MyCode83/godirb"
  url "https://github.com/MyCode83/godirb/archive/refs/tags/v1.4.2.tar.gz"
  sha256 "db1a66cb9c740bf725d16e36d71300ca63afe332b0dc9b8456bb02de2af21874"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "."
  end

  test do
    system "#{bin}/godirb", "--help"
  end
end
