# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Godirb < Formula
  desc "Fast and easy-to-use directory brute-forcer written in go"
  homepage "https://github.com/MyCode83/godirb"
  url "https://github.com/MyCode83/godirb/archive/refs/tags/v1.3.5.tar.gz"
  sha256 "b68cb5975a15856dc025ee4981bc556c46a418d4bd5cc374e8583154150d75be"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "."
  end

  test do
    system "#{bin}/godirb", "--help"
  end
end
