# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Godirb < Formula
  desc "Fast and easy-to-use directory brute-forcer written in go"
  homepage "https://github.com/MyCode83/godirb"
  url "https://github.com/MyCode83/godirb/archive/refs/tags/v1.4.1.tar.gz"
  sha256 "548774fbca2241a527a856b08ccd7fb95220567ba39bb5ca0c4fa97dec54b09e"
  license "MIT"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "."
  end

  test do
    system "#{bin}/godirb", "--help"
  end
end
